import requests
import random

lat = 40.1106
lon = -88.2073
conversion = 1 / 55.2428
radius = 75

url = 'http://barleynet.herokuapp.com'
#url = 'http://localhost:3000'

for i in range(12):
  d = {
    'latitude': lat + (random.random()*2-1)*radius*conversion,
    'longitude': lon + (random.random()*2-1)*radius*conversion}
  r = requests.post(url + '/api/location', data=d)
  r = r.json()
  
  d2 = {
    'location': r['_id'],
    'field': '57ddd756e59ee060ec05a881',
    'description': 'Autogenerated point',
    #'red_flags': True,
    'yield': 100 + 100000 * random.random(),
    'yield_rate': 0.65 + 0.35 * random.random()
  }

  r = requests.post(url + '/api/logs', data=d2);
  print(r)
  print(r.json())